name: development
on:
  - push
  - pull_request
jobs:
  introspect:
    name: introspect
    runs-on: ubuntu-latest
    container: node:16
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://groovox:groovox@postgres:5432/groovox
      POSTGRES_URL: postgresql://postgres:5432/groovox
      POSTGRES_USER: groovox
      POSTGRES_PASSWORD: groovox
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v1
        with:
          url: ${{ format('jdbc:{0}', env.POSTGRES_URL) }}
          user: ${{ env.POSTGRES_USER }}
          password: ${{ env.POSTGRES_PASSWORD }}
          locations: filesystem:./database/migrations
      - run: npm ci
      - run: chmod -R 777 .
      - run: cp packages/plugin-database/schema.template.prisma packages/plugin-database/schema.prisma
      - run: npm run --workspace @groovox/plugin-database introspect:raw
      - run: npm run generate:database
      - uses: actions/upload-artifact@v2
        with:
          name: schema.prisma
          path: packages/plugin-database/schema.prisma
  jest:
    name: jest
    runs-on: ubuntu-latest
    container: node:16
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://groovox:groovox@postgres:5432/groovox
      POSTGRES_URL: postgresql://postgres:5432/groovox
      POSTGRES_USER: groovox
      POSTGRES_PASSWORD: groovox
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v1
        with:
          url: ${{ format('jdbc:{0}', env.POSTGRES_URL) }}
          user: ${{ env.POSTGRES_USER }}
          password: ${{ env.POSTGRES_PASSWORD }}
          locations: filesystem:./database/migrations
      - run: npm ci
      - run: chmod -R 777 .
      - run: npm run generate:database
      - run: npm run generate:graphql
      - run: npm run build
      - run: npm run test
